// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: management/v1/management.proto

package managementv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/zachorosz/byom/proto/management/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ManagementServiceName is the fully-qualified name of the ManagementService service.
	ManagementServiceName = "management.v1.ManagementService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ManagementServiceCreateLocationProcedure is the fully-qualified name of the ManagementService's
	// CreateLocation RPC.
	ManagementServiceCreateLocationProcedure = "/management.v1.ManagementService/CreateLocation"
	// ManagementServiceListLocationsProcedure is the fully-qualified name of the ManagementService's
	// ListLocations RPC.
	ManagementServiceListLocationsProcedure = "/management.v1.ManagementService/ListLocations"
	// ManagementServiceGetLocationProcedure is the fully-qualified name of the ManagementService's
	// GetLocation RPC.
	ManagementServiceGetLocationProcedure = "/management.v1.ManagementService/GetLocation"
	// ManagementServiceUpdateLocationProcedure is the fully-qualified name of the ManagementService's
	// UpdateLocation RPC.
	ManagementServiceUpdateLocationProcedure = "/management.v1.ManagementService/UpdateLocation"
	// ManagementServiceDeleteLocationProcedure is the fully-qualified name of the ManagementService's
	// DeleteLocation RPC.
	ManagementServiceDeleteLocationProcedure = "/management.v1.ManagementService/DeleteLocation"
	// ManagementServiceScanLocationProcedure is the fully-qualified name of the ManagementService's
	// ScanLocation RPC.
	ManagementServiceScanLocationProcedure = "/management.v1.ManagementService/ScanLocation"
	// ManagementServiceListScansProcedure is the fully-qualified name of the ManagementService's
	// ListScans RPC.
	ManagementServiceListScansProcedure = "/management.v1.ManagementService/ListScans"
	// ManagementServiceGetScanProcedure is the fully-qualified name of the ManagementService's GetScan
	// RPC.
	ManagementServiceGetScanProcedure = "/management.v1.ManagementService/GetScan"
	// ManagementServiceCancelScanProcedure is the fully-qualified name of the ManagementService's
	// CancelScan RPC.
	ManagementServiceCancelScanProcedure = "/management.v1.ManagementService/CancelScan"
)

// ManagementServiceClient is a client for the management.v1.ManagementService service.
type ManagementServiceClient interface {
	CreateLocation(context.Context, *v1.CreateLocationRequest) (*v1.CreateLocationResponse, error)
	ListLocations(context.Context, *v1.ListLocationsRequest) (*v1.ListLocationsResponse, error)
	GetLocation(context.Context, *v1.GetLocationRequest) (*v1.GetLocationResponse, error)
	UpdateLocation(context.Context, *v1.UpdateLocationRequest) (*v1.UpdateLocationResponse, error)
	DeleteLocation(context.Context, *v1.DeleteLocationRequest) (*v1.DeleteLocationResponse, error)
	ScanLocation(context.Context, *v1.ScanLocationRequest) (*v1.ScanLocationResponse, error)
	ListScans(context.Context, *v1.ListScansRequest) (*v1.ListScansResponse, error)
	GetScan(context.Context, *v1.GetScanRequest) (*v1.GetScanResponse, error)
	CancelScan(context.Context, *v1.CancelScanRequest) (*v1.CancelScanResponse, error)
}

// NewManagementServiceClient constructs a client for the management.v1.ManagementService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewManagementServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ManagementServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	managementServiceMethods := v1.File_management_v1_management_proto.Services().ByName("ManagementService").Methods()
	return &managementServiceClient{
		createLocation: connect.NewClient[v1.CreateLocationRequest, v1.CreateLocationResponse](
			httpClient,
			baseURL+ManagementServiceCreateLocationProcedure,
			connect.WithSchema(managementServiceMethods.ByName("CreateLocation")),
			connect.WithClientOptions(opts...),
		),
		listLocations: connect.NewClient[v1.ListLocationsRequest, v1.ListLocationsResponse](
			httpClient,
			baseURL+ManagementServiceListLocationsProcedure,
			connect.WithSchema(managementServiceMethods.ByName("ListLocations")),
			connect.WithClientOptions(opts...),
		),
		getLocation: connect.NewClient[v1.GetLocationRequest, v1.GetLocationResponse](
			httpClient,
			baseURL+ManagementServiceGetLocationProcedure,
			connect.WithSchema(managementServiceMethods.ByName("GetLocation")),
			connect.WithClientOptions(opts...),
		),
		updateLocation: connect.NewClient[v1.UpdateLocationRequest, v1.UpdateLocationResponse](
			httpClient,
			baseURL+ManagementServiceUpdateLocationProcedure,
			connect.WithSchema(managementServiceMethods.ByName("UpdateLocation")),
			connect.WithClientOptions(opts...),
		),
		deleteLocation: connect.NewClient[v1.DeleteLocationRequest, v1.DeleteLocationResponse](
			httpClient,
			baseURL+ManagementServiceDeleteLocationProcedure,
			connect.WithSchema(managementServiceMethods.ByName("DeleteLocation")),
			connect.WithClientOptions(opts...),
		),
		scanLocation: connect.NewClient[v1.ScanLocationRequest, v1.ScanLocationResponse](
			httpClient,
			baseURL+ManagementServiceScanLocationProcedure,
			connect.WithSchema(managementServiceMethods.ByName("ScanLocation")),
			connect.WithClientOptions(opts...),
		),
		listScans: connect.NewClient[v1.ListScansRequest, v1.ListScansResponse](
			httpClient,
			baseURL+ManagementServiceListScansProcedure,
			connect.WithSchema(managementServiceMethods.ByName("ListScans")),
			connect.WithClientOptions(opts...),
		),
		getScan: connect.NewClient[v1.GetScanRequest, v1.GetScanResponse](
			httpClient,
			baseURL+ManagementServiceGetScanProcedure,
			connect.WithSchema(managementServiceMethods.ByName("GetScan")),
			connect.WithClientOptions(opts...),
		),
		cancelScan: connect.NewClient[v1.CancelScanRequest, v1.CancelScanResponse](
			httpClient,
			baseURL+ManagementServiceCancelScanProcedure,
			connect.WithSchema(managementServiceMethods.ByName("CancelScan")),
			connect.WithClientOptions(opts...),
		),
	}
}

// managementServiceClient implements ManagementServiceClient.
type managementServiceClient struct {
	createLocation *connect.Client[v1.CreateLocationRequest, v1.CreateLocationResponse]
	listLocations  *connect.Client[v1.ListLocationsRequest, v1.ListLocationsResponse]
	getLocation    *connect.Client[v1.GetLocationRequest, v1.GetLocationResponse]
	updateLocation *connect.Client[v1.UpdateLocationRequest, v1.UpdateLocationResponse]
	deleteLocation *connect.Client[v1.DeleteLocationRequest, v1.DeleteLocationResponse]
	scanLocation   *connect.Client[v1.ScanLocationRequest, v1.ScanLocationResponse]
	listScans      *connect.Client[v1.ListScansRequest, v1.ListScansResponse]
	getScan        *connect.Client[v1.GetScanRequest, v1.GetScanResponse]
	cancelScan     *connect.Client[v1.CancelScanRequest, v1.CancelScanResponse]
}

// CreateLocation calls management.v1.ManagementService.CreateLocation.
func (c *managementServiceClient) CreateLocation(ctx context.Context, req *v1.CreateLocationRequest) (*v1.CreateLocationResponse, error) {
	response, err := c.createLocation.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListLocations calls management.v1.ManagementService.ListLocations.
func (c *managementServiceClient) ListLocations(ctx context.Context, req *v1.ListLocationsRequest) (*v1.ListLocationsResponse, error) {
	response, err := c.listLocations.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetLocation calls management.v1.ManagementService.GetLocation.
func (c *managementServiceClient) GetLocation(ctx context.Context, req *v1.GetLocationRequest) (*v1.GetLocationResponse, error) {
	response, err := c.getLocation.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateLocation calls management.v1.ManagementService.UpdateLocation.
func (c *managementServiceClient) UpdateLocation(ctx context.Context, req *v1.UpdateLocationRequest) (*v1.UpdateLocationResponse, error) {
	response, err := c.updateLocation.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteLocation calls management.v1.ManagementService.DeleteLocation.
func (c *managementServiceClient) DeleteLocation(ctx context.Context, req *v1.DeleteLocationRequest) (*v1.DeleteLocationResponse, error) {
	response, err := c.deleteLocation.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ScanLocation calls management.v1.ManagementService.ScanLocation.
func (c *managementServiceClient) ScanLocation(ctx context.Context, req *v1.ScanLocationRequest) (*v1.ScanLocationResponse, error) {
	response, err := c.scanLocation.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListScans calls management.v1.ManagementService.ListScans.
func (c *managementServiceClient) ListScans(ctx context.Context, req *v1.ListScansRequest) (*v1.ListScansResponse, error) {
	response, err := c.listScans.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetScan calls management.v1.ManagementService.GetScan.
func (c *managementServiceClient) GetScan(ctx context.Context, req *v1.GetScanRequest) (*v1.GetScanResponse, error) {
	response, err := c.getScan.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CancelScan calls management.v1.ManagementService.CancelScan.
func (c *managementServiceClient) CancelScan(ctx context.Context, req *v1.CancelScanRequest) (*v1.CancelScanResponse, error) {
	response, err := c.cancelScan.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ManagementServiceHandler is an implementation of the management.v1.ManagementService service.
type ManagementServiceHandler interface {
	CreateLocation(context.Context, *v1.CreateLocationRequest) (*v1.CreateLocationResponse, error)
	ListLocations(context.Context, *v1.ListLocationsRequest) (*v1.ListLocationsResponse, error)
	GetLocation(context.Context, *v1.GetLocationRequest) (*v1.GetLocationResponse, error)
	UpdateLocation(context.Context, *v1.UpdateLocationRequest) (*v1.UpdateLocationResponse, error)
	DeleteLocation(context.Context, *v1.DeleteLocationRequest) (*v1.DeleteLocationResponse, error)
	ScanLocation(context.Context, *v1.ScanLocationRequest) (*v1.ScanLocationResponse, error)
	ListScans(context.Context, *v1.ListScansRequest) (*v1.ListScansResponse, error)
	GetScan(context.Context, *v1.GetScanRequest) (*v1.GetScanResponse, error)
	CancelScan(context.Context, *v1.CancelScanRequest) (*v1.CancelScanResponse, error)
}

// NewManagementServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewManagementServiceHandler(svc ManagementServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	managementServiceMethods := v1.File_management_v1_management_proto.Services().ByName("ManagementService").Methods()
	managementServiceCreateLocationHandler := connect.NewUnaryHandlerSimple(
		ManagementServiceCreateLocationProcedure,
		svc.CreateLocation,
		connect.WithSchema(managementServiceMethods.ByName("CreateLocation")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceListLocationsHandler := connect.NewUnaryHandlerSimple(
		ManagementServiceListLocationsProcedure,
		svc.ListLocations,
		connect.WithSchema(managementServiceMethods.ByName("ListLocations")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceGetLocationHandler := connect.NewUnaryHandlerSimple(
		ManagementServiceGetLocationProcedure,
		svc.GetLocation,
		connect.WithSchema(managementServiceMethods.ByName("GetLocation")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceUpdateLocationHandler := connect.NewUnaryHandlerSimple(
		ManagementServiceUpdateLocationProcedure,
		svc.UpdateLocation,
		connect.WithSchema(managementServiceMethods.ByName("UpdateLocation")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceDeleteLocationHandler := connect.NewUnaryHandlerSimple(
		ManagementServiceDeleteLocationProcedure,
		svc.DeleteLocation,
		connect.WithSchema(managementServiceMethods.ByName("DeleteLocation")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceScanLocationHandler := connect.NewUnaryHandlerSimple(
		ManagementServiceScanLocationProcedure,
		svc.ScanLocation,
		connect.WithSchema(managementServiceMethods.ByName("ScanLocation")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceListScansHandler := connect.NewUnaryHandlerSimple(
		ManagementServiceListScansProcedure,
		svc.ListScans,
		connect.WithSchema(managementServiceMethods.ByName("ListScans")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceGetScanHandler := connect.NewUnaryHandlerSimple(
		ManagementServiceGetScanProcedure,
		svc.GetScan,
		connect.WithSchema(managementServiceMethods.ByName("GetScan")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceCancelScanHandler := connect.NewUnaryHandlerSimple(
		ManagementServiceCancelScanProcedure,
		svc.CancelScan,
		connect.WithSchema(managementServiceMethods.ByName("CancelScan")),
		connect.WithHandlerOptions(opts...),
	)
	return "/management.v1.ManagementService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ManagementServiceCreateLocationProcedure:
			managementServiceCreateLocationHandler.ServeHTTP(w, r)
		case ManagementServiceListLocationsProcedure:
			managementServiceListLocationsHandler.ServeHTTP(w, r)
		case ManagementServiceGetLocationProcedure:
			managementServiceGetLocationHandler.ServeHTTP(w, r)
		case ManagementServiceUpdateLocationProcedure:
			managementServiceUpdateLocationHandler.ServeHTTP(w, r)
		case ManagementServiceDeleteLocationProcedure:
			managementServiceDeleteLocationHandler.ServeHTTP(w, r)
		case ManagementServiceScanLocationProcedure:
			managementServiceScanLocationHandler.ServeHTTP(w, r)
		case ManagementServiceListScansProcedure:
			managementServiceListScansHandler.ServeHTTP(w, r)
		case ManagementServiceGetScanProcedure:
			managementServiceGetScanHandler.ServeHTTP(w, r)
		case ManagementServiceCancelScanProcedure:
			managementServiceCancelScanHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedManagementServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedManagementServiceHandler struct{}

func (UnimplementedManagementServiceHandler) CreateLocation(context.Context, *v1.CreateLocationRequest) (*v1.CreateLocationResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("management.v1.ManagementService.CreateLocation is not implemented"))
}

func (UnimplementedManagementServiceHandler) ListLocations(context.Context, *v1.ListLocationsRequest) (*v1.ListLocationsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("management.v1.ManagementService.ListLocations is not implemented"))
}

func (UnimplementedManagementServiceHandler) GetLocation(context.Context, *v1.GetLocationRequest) (*v1.GetLocationResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("management.v1.ManagementService.GetLocation is not implemented"))
}

func (UnimplementedManagementServiceHandler) UpdateLocation(context.Context, *v1.UpdateLocationRequest) (*v1.UpdateLocationResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("management.v1.ManagementService.UpdateLocation is not implemented"))
}

func (UnimplementedManagementServiceHandler) DeleteLocation(context.Context, *v1.DeleteLocationRequest) (*v1.DeleteLocationResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("management.v1.ManagementService.DeleteLocation is not implemented"))
}

func (UnimplementedManagementServiceHandler) ScanLocation(context.Context, *v1.ScanLocationRequest) (*v1.ScanLocationResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("management.v1.ManagementService.ScanLocation is not implemented"))
}

func (UnimplementedManagementServiceHandler) ListScans(context.Context, *v1.ListScansRequest) (*v1.ListScansResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("management.v1.ManagementService.ListScans is not implemented"))
}

func (UnimplementedManagementServiceHandler) GetScan(context.Context, *v1.GetScanRequest) (*v1.GetScanResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("management.v1.ManagementService.GetScan is not implemented"))
}

func (UnimplementedManagementServiceHandler) CancelScan(context.Context, *v1.CancelScanRequest) (*v1.CancelScanResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("management.v1.ManagementService.CancelScan is not implemented"))
}
