// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: management/v1/location.proto

package managementv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_management_v1_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_management_v1_location_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Location) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_management_v1_location_proto protoreflect.FileDescriptor

const file_management_v1_location_proto_rawDesc = "" +
	"\n" +
	"\x1cmanagement/v1/location.proto\x12\rmanagement.v1\x1a\x1bbuf/validate/validate.proto\"C\n" +
	"\bLocation\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xd8\x01\x01r\x03\xb0\x01\x01R\x02id\x12\x1a\n" +
	"\x04path\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04pathB\xb3\x01\n" +
	"\x11com.management.v1B\rLocationProtoP\x01Z:github.com/zachorosz/byom/proto/management/v1;managementv1\xa2\x02\x03MXX\xaa\x02\rManagement.V1\xca\x02\rManagement\\V1\xe2\x02\x19Management\\V1\\GPBMetadata\xea\x02\x0eManagement::V1b\x06proto3"

var (
	file_management_v1_location_proto_rawDescOnce sync.Once
	file_management_v1_location_proto_rawDescData []byte
)

func file_management_v1_location_proto_rawDescGZIP() []byte {
	file_management_v1_location_proto_rawDescOnce.Do(func() {
		file_management_v1_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_v1_location_proto_rawDesc), len(file_management_v1_location_proto_rawDesc)))
	})
	return file_management_v1_location_proto_rawDescData
}

var file_management_v1_location_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_management_v1_location_proto_goTypes = []any{
	(*Location)(nil), // 0: management.v1.Location
}
var file_management_v1_location_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_management_v1_location_proto_init() }
func file_management_v1_location_proto_init() {
	if File_management_v1_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_v1_location_proto_rawDesc), len(file_management_v1_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_management_v1_location_proto_goTypes,
		DependencyIndexes: file_management_v1_location_proto_depIdxs,
		MessageInfos:      file_management_v1_location_proto_msgTypes,
	}.Build()
	File_management_v1_location_proto = out.File
	file_management_v1_location_proto_goTypes = nil
	file_management_v1_location_proto_depIdxs = nil
}
