// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: management/v1/management.proto

package managementv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocationRequest) Reset() {
	*x = CreateLocationRequest{}
	mi := &file_management_v1_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocationRequest) ProtoMessage() {}

func (x *CreateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocationRequest.ProtoReflect.Descriptor instead.
func (*CreateLocationRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLocationRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type CreateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocationResponse) Reset() {
	*x = CreateLocationResponse{}
	mi := &file_management_v1_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocationResponse) ProtoMessage() {}

func (x *CreateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocationResponse.ProtoReflect.Descriptor instead.
func (*CreateLocationResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLocationResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type ListLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocationsRequest) Reset() {
	*x = ListLocationsRequest{}
	mi := &file_management_v1_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsRequest) ProtoMessage() {}

func (x *ListLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsRequest.ProtoReflect.Descriptor instead.
func (*ListLocationsRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{2}
}

func (x *ListLocationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLocationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Location            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocationsResponse) Reset() {
	*x = ListLocationsResponse{}
	mi := &file_management_v1_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsResponse) ProtoMessage() {}

func (x *ListLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsResponse.ProtoReflect.Descriptor instead.
func (*ListLocationsResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{3}
}

func (x *ListLocationsResponse) GetItems() []*Location {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListLocationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	mi := &file_management_v1_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{4}
}

func (x *GetLocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationResponse) Reset() {
	*x = GetLocationResponse{}
	mi := &file_management_v1_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationResponse) ProtoMessage() {}

func (x *GetLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationResponse.ProtoReflect.Descriptor instead.
func (*GetLocationResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{5}
}

func (x *GetLocationResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_management_v1_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLocationRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type UpdateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationResponse) Reset() {
	*x = UpdateLocationResponse{}
	mi := &file_management_v1_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationResponse) ProtoMessage() {}

func (x *UpdateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLocationResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type DeleteLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLocationRequest) Reset() {
	*x = DeleteLocationRequest{}
	mi := &file_management_v1_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLocationRequest) ProtoMessage() {}

func (x *DeleteLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLocationRequest.ProtoReflect.Descriptor instead.
func (*DeleteLocationRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLocationResponse) Reset() {
	*x = DeleteLocationResponse{}
	mi := &file_management_v1_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLocationResponse) ProtoMessage() {}

func (x *DeleteLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLocationResponse.ProtoReflect.Descriptor instead.
func (*DeleteLocationResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{9}
}

type ScanLocationRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	LocationId string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	// Queue every synced dir for reparsing, not just the changed ones.
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanLocationRequest) Reset() {
	*x = ScanLocationRequest{}
	mi := &file_management_v1_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanLocationRequest) ProtoMessage() {}

func (x *ScanLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanLocationRequest.ProtoReflect.Descriptor instead.
func (*ScanLocationRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{10}
}

func (x *ScanLocationRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *ScanLocationRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ScanLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scan          *Scan                  `protobuf:"bytes,1,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanLocationResponse) Reset() {
	*x = ScanLocationResponse{}
	mi := &file_management_v1_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanLocationResponse) ProtoMessage() {}

func (x *ScanLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanLocationResponse.ProtoReflect.Descriptor instead.
func (*ScanLocationResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{11}
}

func (x *ScanLocationResponse) GetScan() *Scan {
	if x != nil {
		return x.Scan
	}
	return nil
}

type ListScansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	LocationId    string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	State         ScanState              `protobuf:"varint,4,opt,name=state,proto3,enum=management.v1.ScanState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScansRequest) Reset() {
	*x = ListScansRequest{}
	mi := &file_management_v1_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScansRequest) ProtoMessage() {}

func (x *ListScansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScansRequest.ProtoReflect.Descriptor instead.
func (*ListScansRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{12}
}

func (x *ListScansRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListScansRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListScansRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *ListScansRequest) GetState() ScanState {
	if x != nil {
		return x.State
	}
	return ScanState_SCAN_STATE_UNSPECIFIED
}

type ListScansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Scan                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScansResponse) Reset() {
	*x = ListScansResponse{}
	mi := &file_management_v1_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScansResponse) ProtoMessage() {}

func (x *ListScansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScansResponse.ProtoReflect.Descriptor instead.
func (*ListScansResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{13}
}

func (x *ListScansResponse) GetItems() []*Scan {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListScansResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanRequest) Reset() {
	*x = GetScanRequest{}
	mi := &file_management_v1_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanRequest) ProtoMessage() {}

func (x *GetScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanRequest.ProtoReflect.Descriptor instead.
func (*GetScanRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{14}
}

func (x *GetScanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scan          *Scan                  `protobuf:"bytes,1,opt,name=scan,proto3" json:"scan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScanResponse) Reset() {
	*x = GetScanResponse{}
	mi := &file_management_v1_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanResponse) ProtoMessage() {}

func (x *GetScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanResponse.ProtoReflect.Descriptor instead.
func (*GetScanResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{15}
}

func (x *GetScanResponse) GetScan() *Scan {
	if x != nil {
		return x.Scan
	}
	return nil
}

type CancelScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelScanRequest) Reset() {
	*x = CancelScanRequest{}
	mi := &file_management_v1_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScanRequest) ProtoMessage() {}

func (x *CancelScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScanRequest.ProtoReflect.Descriptor instead.
func (*CancelScanRequest) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{16}
}

func (x *CancelScanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelScanResponse) Reset() {
	*x = CancelScanResponse{}
	mi := &file_management_v1_management_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelScanResponse) ProtoMessage() {}

func (x *CancelScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_management_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelScanResponse.ProtoReflect.Descriptor instead.
func (*CancelScanResponse) Descriptor() ([]byte, []int) {
	return file_management_v1_management_proto_rawDescGZIP(), []int{17}
}

var File_management_v1_management_proto protoreflect.FileDescriptor

const file_management_v1_management_proto_rawDesc = "" +
	"\n" +
	"\x1emanagement/v1/management.proto\x12\rmanagement.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cmanagement/v1/location.proto\x1a\x18management/v1/scan.proto\"T\n" +
	"\x15CreateLocationRequest\x12;\n" +
	"\blocation\x18\x01 \x01(\v2\x17.management.v1.LocationB\x06\xbaH\x03\xc8\x01\x01R\blocation\"M\n" +
	"\x16CreateLocationResponse\x123\n" +
	"\blocation\x18\x01 \x01(\v2\x17.management.v1.LocationR\blocation\"R\n" +
	"\x14ListLocationsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"n\n" +
	"\x15ListLocationsResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.management.v1.LocationR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\",\n" +
	"\x12GetLocationRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id\"J\n" +
	"\x13GetLocationResponse\x123\n" +
	"\blocation\x18\x01 \x01(\v2\x17.management.v1.LocationR\blocation\"T\n" +
	"\x15UpdateLocationRequest\x12;\n" +
	"\blocation\x18\x01 \x01(\v2\x17.management.v1.LocationB\x06\xbaH\x03\xc8\x01\x01R\blocation\"M\n" +
	"\x16UpdateLocationResponse\x123\n" +
	"\blocation\x18\x01 \x01(\v2\x17.management.v1.LocationR\blocation\"/\n" +
	"\x15DeleteLocationRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id\"\x18\n" +
	"\x16DeleteLocationResponse\"T\n" +
	"\x13ScanLocationRequest\x12'\n" +
	"\vlocation_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"locationId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"?\n" +
	"\x14ScanLocationResponse\x12'\n" +
	"\x04scan\x18\x01 \x01(\v2\x13.management.v1.ScanR\x04scan\"\x9f\x01\n" +
	"\x10ListScansRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\x12.\n" +
	"\x05state\x18\x04 \x01(\x0e2\x18.management.v1.ScanStateR\x05state\"f\n" +
	"\x11ListScansResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.management.v1.ScanR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"(\n" +
	"\x0eGetScanRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id\":\n" +
	"\x0fGetScanResponse\x12'\n" +
	"\x04scan\x18\x01 \x01(\v2\x13.management.v1.ScanR\x04scan\"#\n" +
	"\x11CancelScanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12CancelScanResponse2\xba\x06\n" +
	"\x11ManagementService\x12_\n" +
	"\x0eCreateLocation\x12$.management.v1.CreateLocationRequest\x1a%.management.v1.CreateLocationResponse\"\x00\x12\\\n" +
	"\rListLocations\x12#.management.v1.ListLocationsRequest\x1a$.management.v1.ListLocationsResponse\"\x00\x12V\n" +
	"\vGetLocation\x12!.management.v1.GetLocationRequest\x1a\".management.v1.GetLocationResponse\"\x00\x12_\n" +
	"\x0eUpdateLocation\x12$.management.v1.UpdateLocationRequest\x1a%.management.v1.UpdateLocationResponse\"\x00\x12_\n" +
	"\x0eDeleteLocation\x12$.management.v1.DeleteLocationRequest\x1a%.management.v1.DeleteLocationResponse\"\x00\x12Y\n" +
	"\fScanLocation\x12\".management.v1.ScanLocationRequest\x1a#.management.v1.ScanLocationResponse\"\x00\x12P\n" +
	"\tListScans\x12\x1f.management.v1.ListScansRequest\x1a .management.v1.ListScansResponse\"\x00\x12J\n" +
	"\aGetScan\x12\x1d.management.v1.GetScanRequest\x1a\x1e.management.v1.GetScanResponse\"\x00\x12S\n" +
	"\n" +
	"CancelScan\x12 .management.v1.CancelScanRequest\x1a!.management.v1.CancelScanResponse\"\x00B\xb5\x01\n" +
	"\x11com.management.v1B\x0fManagementProtoP\x01Z:github.com/zachorosz/byom/proto/management/v1;managementv1\xa2\x02\x03MXX\xaa\x02\rManagement.V1\xca\x02\rManagement\\V1\xe2\x02\x19Management\\V1\\GPBMetadata\xea\x02\x0eManagement::V1b\x06proto3"

var (
	file_management_v1_management_proto_rawDescOnce sync.Once
	file_management_v1_management_proto_rawDescData []byte
)

func file_management_v1_management_proto_rawDescGZIP() []byte {
	file_management_v1_management_proto_rawDescOnce.Do(func() {
		file_management_v1_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_v1_management_proto_rawDesc), len(file_management_v1_management_proto_rawDesc)))
	})
	return file_management_v1_management_proto_rawDescData
}

var file_management_v1_management_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_management_v1_management_proto_goTypes = []any{
	(*CreateLocationRequest)(nil),  // 0: management.v1.CreateLocationRequest
	(*CreateLocationResponse)(nil), // 1: management.v1.CreateLocationResponse
	(*ListLocationsRequest)(nil),   // 2: management.v1.ListLocationsRequest
	(*ListLocationsResponse)(nil),  // 3: management.v1.ListLocationsResponse
	(*GetLocationRequest)(nil),     // 4: management.v1.GetLocationRequest
	(*GetLocationResponse)(nil),    // 5: management.v1.GetLocationResponse
	(*UpdateLocationRequest)(nil),  // 6: management.v1.UpdateLocationRequest
	(*UpdateLocationResponse)(nil), // 7: management.v1.UpdateLocationResponse
	(*DeleteLocationRequest)(nil),  // 8: management.v1.DeleteLocationRequest
	(*DeleteLocationResponse)(nil), // 9: management.v1.DeleteLocationResponse
	(*ScanLocationRequest)(nil),    // 10: management.v1.ScanLocationRequest
	(*ScanLocationResponse)(nil),   // 11: management.v1.ScanLocationResponse
	(*ListScansRequest)(nil),       // 12: management.v1.ListScansRequest
	(*ListScansResponse)(nil),      // 13: management.v1.ListScansResponse
	(*GetScanRequest)(nil),         // 14: management.v1.GetScanRequest
	(*GetScanResponse)(nil),        // 15: management.v1.GetScanResponse
	(*CancelScanRequest)(nil),      // 16: management.v1.CancelScanRequest
	(*CancelScanResponse)(nil),     // 17: management.v1.CancelScanResponse
	(*Location)(nil),               // 18: management.v1.Location
	(*Scan)(nil),                   // 19: management.v1.Scan
	(ScanState)(0),                 // 20: management.v1.ScanState
}
var file_management_v1_management_proto_depIdxs = []int32{
	18, // 0: management.v1.CreateLocationRequest.location:type_name -> management.v1.Location
	18, // 1: management.v1.CreateLocationResponse.location:type_name -> management.v1.Location
	18, // 2: management.v1.ListLocationsResponse.items:type_name -> management.v1.Location
	18, // 3: management.v1.GetLocationResponse.location:type_name -> management.v1.Location
	18, // 4: management.v1.UpdateLocationRequest.location:type_name -> management.v1.Location
	18, // 5: management.v1.UpdateLocationResponse.location:type_name -> management.v1.Location
	19, // 6: management.v1.ScanLocationResponse.scan:type_name -> management.v1.Scan
	20, // 7: management.v1.ListScansRequest.state:type_name -> management.v1.ScanState
	19, // 8: management.v1.ListScansResponse.items:type_name -> management.v1.Scan
	19, // 9: management.v1.GetScanResponse.scan:type_name -> management.v1.Scan
	0,  // 10: management.v1.ManagementService.CreateLocation:input_type -> management.v1.CreateLocationRequest
	2,  // 11: management.v1.ManagementService.ListLocations:input_type -> management.v1.ListLocationsRequest
	4,  // 12: management.v1.ManagementService.GetLocation:input_type -> management.v1.GetLocationRequest
	6,  // 13: management.v1.ManagementService.UpdateLocation:input_type -> management.v1.UpdateLocationRequest
	8,  // 14: management.v1.ManagementService.DeleteLocation:input_type -> management.v1.DeleteLocationRequest
	10, // 15: management.v1.ManagementService.ScanLocation:input_type -> management.v1.ScanLocationRequest
	12, // 16: management.v1.ManagementService.ListScans:input_type -> management.v1.ListScansRequest
	14, // 17: management.v1.ManagementService.GetScan:input_type -> management.v1.GetScanRequest
	16, // 18: management.v1.ManagementService.CancelScan:input_type -> management.v1.CancelScanRequest
	1,  // 19: management.v1.ManagementService.CreateLocation:output_type -> management.v1.CreateLocationResponse
	3,  // 20: management.v1.ManagementService.ListLocations:output_type -> management.v1.ListLocationsResponse
	5,  // 21: management.v1.ManagementService.GetLocation:output_type -> management.v1.GetLocationResponse
	7,  // 22: management.v1.ManagementService.UpdateLocation:output_type -> management.v1.UpdateLocationResponse
	9,  // 23: management.v1.ManagementService.DeleteLocation:output_type -> management.v1.DeleteLocationResponse
	11, // 24: management.v1.ManagementService.ScanLocation:output_type -> management.v1.ScanLocationResponse
	13, // 25: management.v1.ManagementService.ListScans:output_type -> management.v1.ListScansResponse
	15, // 26: management.v1.ManagementService.GetScan:output_type -> management.v1.GetScanResponse
	17, // 27: management.v1.ManagementService.CancelScan:output_type -> management.v1.CancelScanResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_management_v1_management_proto_init() }
func file_management_v1_management_proto_init() {
	if File_management_v1_management_proto != nil {
		return
	}
	file_management_v1_location_proto_init()
	file_management_v1_scan_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_v1_management_proto_rawDesc), len(file_management_v1_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_management_v1_management_proto_goTypes,
		DependencyIndexes: file_management_v1_management_proto_depIdxs,
		MessageInfos:      file_management_v1_management_proto_msgTypes,
	}.Build()
	File_management_v1_management_proto = out.File
	file_management_v1_management_proto_goTypes = nil
	file_management_v1_management_proto_depIdxs = nil
}
