// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: management/v1/scan.proto

package managementv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanState int32

const (
	ScanState_SCAN_STATE_UNSPECIFIED ScanState = 0
	ScanState_SCAN_STATE_RUNNING     ScanState = 1
	ScanState_SCAN_STATE_CANCELLING  ScanState = 2
	ScanState_SCAN_STATE_DONE        ScanState = 3
	ScanState_SCAN_STATE_FAILED      ScanState = 4
	ScanState_SCAN_STATE_ABORTED     ScanState = 5
)

// Enum value maps for ScanState.
var (
	ScanState_name = map[int32]string{
		0: "SCAN_STATE_UNSPECIFIED",
		1: "SCAN_STATE_RUNNING",
		2: "SCAN_STATE_CANCELLING",
		3: "SCAN_STATE_DONE",
		4: "SCAN_STATE_FAILED",
		5: "SCAN_STATE_ABORTED",
	}
	ScanState_value = map[string]int32{
		"SCAN_STATE_UNSPECIFIED": 0,
		"SCAN_STATE_RUNNING":     1,
		"SCAN_STATE_CANCELLING":  2,
		"SCAN_STATE_DONE":        3,
		"SCAN_STATE_FAILED":      4,
		"SCAN_STATE_ABORTED":     5,
	}
)

func (x ScanState) Enum() *ScanState {
	p := new(ScanState)
	*p = x
	return p
}

func (x ScanState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScanState) Descriptor() protoreflect.EnumDescriptor {
	return file_management_v1_scan_proto_enumTypes[0].Descriptor()
}

func (ScanState) Type() protoreflect.EnumType {
	return &file_management_v1_scan_proto_enumTypes[0]
}

func (x ScanState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScanState.Descriptor instead.
func (ScanState) EnumDescriptor() ([]byte, []int) {
	return file_management_v1_scan_proto_rawDescGZIP(), []int{0}
}

type Scan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	State         ScanState              `protobuf:"varint,3,opt,name=state,proto3,enum=management.v1.ScanState" json:"state,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	FinishTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Progress      *Scan_Progress         `protobuf:"bytes,7,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scan) Reset() {
	*x = Scan{}
	mi := &file_management_v1_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scan) ProtoMessage() {}

func (x *Scan) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scan.ProtoReflect.Descriptor instead.
func (*Scan) Descriptor() ([]byte, []int) {
	return file_management_v1_scan_proto_rawDescGZIP(), []int{0}
}

func (x *Scan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Scan) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Scan) GetState() ScanState {
	if x != nil {
		return x.State
	}
	return ScanState_SCAN_STATE_UNSPECIFIED
}

func (x *Scan) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Scan) GetFinishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishTime
	}
	return nil
}

func (x *Scan) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Scan) GetProgress() *Scan_Progress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type Scan_Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirsSeen      int64                  `protobuf:"varint,1,opt,name=dirs_seen,json=dirsSeen,proto3" json:"dirs_seen,omitempty"`
	DirsMissing   int64                  `protobuf:"varint,2,opt,name=dirs_missing,json=dirsMissing,proto3" json:"dirs_missing,omitempty"`
	FilesSeen     int64                  `protobuf:"varint,3,opt,name=files_seen,json=filesSeen,proto3" json:"files_seen,omitempty"`
	FilesMissing  int64                  `protobuf:"varint,4,opt,name=files_missing,json=filesMissing,proto3" json:"files_missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scan_Progress) Reset() {
	*x = Scan_Progress{}
	mi := &file_management_v1_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scan_Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scan_Progress) ProtoMessage() {}

func (x *Scan_Progress) ProtoReflect() protoreflect.Message {
	mi := &file_management_v1_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scan_Progress.ProtoReflect.Descriptor instead.
func (*Scan_Progress) Descriptor() ([]byte, []int) {
	return file_management_v1_scan_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Scan_Progress) GetDirsSeen() int64 {
	if x != nil {
		return x.DirsSeen
	}
	return 0
}

func (x *Scan_Progress) GetDirsMissing() int64 {
	if x != nil {
		return x.DirsMissing
	}
	return 0
}

func (x *Scan_Progress) GetFilesSeen() int64 {
	if x != nil {
		return x.FilesSeen
	}
	return 0
}

func (x *Scan_Progress) GetFilesMissing() int64 {
	if x != nil {
		return x.FilesMissing
	}
	return 0
}

var File_management_v1_scan_proto protoreflect.FileDescriptor

const file_management_v1_scan_proto_rawDesc = "" +
	"\n" +
	"\x18management/v1/scan.proto\x12\rmanagement.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x03\n" +
	"\x04Scan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12.\n" +
	"\x05state\x18\x03 \x01(\x0e2\x18.management.v1.ScanStateR\x05state\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12;\n" +
	"\vfinish_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishTime\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x128\n" +
	"\bprogress\x18\a \x01(\v2\x1c.management.v1.Scan.ProgressR\bprogress\x1a\x8e\x01\n" +
	"\bProgress\x12\x1b\n" +
	"\tdirs_seen\x18\x01 \x01(\x03R\bdirsSeen\x12!\n" +
	"\fdirs_missing\x18\x02 \x01(\x03R\vdirsMissing\x12\x1d\n" +
	"\n" +
	"files_seen\x18\x03 \x01(\x03R\tfilesSeen\x12#\n" +
	"\rfiles_missing\x18\x04 \x01(\x03R\ffilesMissing*\x9e\x01\n" +
	"\tScanState\x12\x1a\n" +
	"\x16SCAN_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SCAN_STATE_RUNNING\x10\x01\x12\x19\n" +
	"\x15SCAN_STATE_CANCELLING\x10\x02\x12\x13\n" +
	"\x0fSCAN_STATE_DONE\x10\x03\x12\x15\n" +
	"\x11SCAN_STATE_FAILED\x10\x04\x12\x16\n" +
	"\x12SCAN_STATE_ABORTED\x10\x05B\xaf\x01\n" +
	"\x11com.management.v1B\tScanProtoP\x01Z:github.com/zachorosz/byom/proto/management/v1;managementv1\xa2\x02\x03MXX\xaa\x02\rManagement.V1\xca\x02\rManagement\\V1\xe2\x02\x19Management\\V1\\GPBMetadata\xea\x02\x0eManagement::V1b\x06proto3"

var (
	file_management_v1_scan_proto_rawDescOnce sync.Once
	file_management_v1_scan_proto_rawDescData []byte
)

func file_management_v1_scan_proto_rawDescGZIP() []byte {
	file_management_v1_scan_proto_rawDescOnce.Do(func() {
		file_management_v1_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_v1_scan_proto_rawDesc), len(file_management_v1_scan_proto_rawDesc)))
	})
	return file_management_v1_scan_proto_rawDescData
}

var file_management_v1_scan_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_management_v1_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_management_v1_scan_proto_goTypes = []any{
	(ScanState)(0),                // 0: management.v1.ScanState
	(*Scan)(nil),                  // 1: management.v1.Scan
	(*Scan_Progress)(nil),         // 2: management.v1.Scan.Progress
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_management_v1_scan_proto_depIdxs = []int32{
	0, // 0: management.v1.Scan.state:type_name -> management.v1.ScanState
	3, // 1: management.v1.Scan.start_time:type_name -> google.protobuf.Timestamp
	3, // 2: management.v1.Scan.finish_time:type_name -> google.protobuf.Timestamp
	2, // 3: management.v1.Scan.progress:type_name -> management.v1.Scan.Progress
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_management_v1_scan_proto_init() }
func file_management_v1_scan_proto_init() {
	if File_management_v1_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_v1_scan_proto_rawDesc), len(file_management_v1_scan_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_management_v1_scan_proto_goTypes,
		DependencyIndexes: file_management_v1_scan_proto_depIdxs,
		EnumInfos:         file_management_v1_scan_proto_enumTypes,
		MessageInfos:      file_management_v1_scan_proto_msgTypes,
	}.Build()
	File_management_v1_scan_proto = out.File
	file_management_v1_scan_proto_goTypes = nil
	file_management_v1_scan_proto_depIdxs = nil
}
